channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.10
  - pip=21.0
  - cadquery=master
  - matplotlib=3.3
  - pip:
      - jupyter-cadquery==3.3.0
      - cadquery-massembly==1.0.0rc0
